### ISSUE TITLE
itstool-2.0.3 uses all system memory

### ISSUE THREAD

**Issue by elkrejzi** [itstool/itstool#15]
When building aisleriot-3.22.3 or gdm-3.26.1 with itstool-2.0.3, the python process (either py2 or py3, doesn't matter which) will use up all the system memory, leading to system lock-up and requiring hard reboot. The problematic locale for aisleriot seems to be "el". Not sure about gdm, I don't think I'll try building it again.

**Comment by shaunix** [comment]
Confirming. The el locale in aisleriot triggers, though that doesn't mean it's the only one. It doesn't happen if itstool is called separately for each XML file, like this:

    for x in ../C/*.xml; do itstool -m el.mo $x; done

But it does happen when running them all at once:

    itstool -m el.mo ../C/*.xml

This makes me think it's some sort of runaway memory leak. Not sure why 2.0.3 would have introduced such a problem.

**Comment by shaunix** [comment]
git bisect tells me the problem was introduced by commit 14f428652bc44d0f65cf21f17afaf1e0b13f0336, which fixed --keep-entities after a libxml2 change that annoyed me.

**Comment by shaunix** [comment]
Fixed. The memory leak was always there, but the new parse options exposed it more. I'll roll a new release this week, because this is pretty critical for people with large DTD-based documents.

**Comment by shaunix** [comment]
Version 2.0.4 released. I strongly recommend upgrading from 2.0.3.

**Comment by heftig** [comment]
The fix causes itstool to segfault here when building rhythmbox (master) on i686. It seems you're freeing something you still need.

**Comment by pullmoll** [comment]
I can confirm that itstool-2.0.4 now segfaults when building gtk-doc on Void Linux.
Also see https://github.com/voidlinux/void-packages/issues/8365

**Comment by shaunix** [comment]
Filed a new bug for the crasher: https://github.com/itstool/itstool/issues/17

**Comment by shaunix** [comment]
I've just committed some changes that I think fix the memory issues. I'd appreciate if people could test before I roll another release.

**Comment by heftig** [comment]
Works for me; thanks.
