### ISSUE TITLE
mallard: allow https for xmlns

### ISSUE THREAD

**Issue by jbicha** [itstool/itstool#29]
Please update the parser to allow identifiers like `xmlns:its="http://www.w3.org/2005/11/its"`to be switched to use https instead of http.

This problem was identified with the mallard help for Evolution.

Originally reported at https://gitlab.gnome.org/GNOME/evolution/issues/90

**Comment by haaninjo** [comment]
> Please update the parser to allow identifiers like xmlns:its="http://www.w3.org/2005/11/its"to be switched to use https instead of http.

I'm not sure that that is a bug. All material that I looked at when I examined the issue in the other bug report emphasizes that namespace names are to be considered unique strings, and not an URI.

For example this w3c recommendation (https://www.w3.org/TR/2009/REC-xml-names-20091208/#ns-decl):

>The namespace name, to serve its intended purpose, SHOULD have the characteristics of uniqueness and persistence. It is not a goal that it be directly usable for retrieval of a schema (if any exists).

I read that as one should not change the protocol of a namespace if one wants to refer to it.

**Comment by shaunix** [comment]
Closing. This just isn't how XML namespaces work. Every XML tool expects them to be character-for-character exact strings.
