### ISSUE TITLE
--join option not working

### ISSUE THREAD

**Issue by momits** [itstool/itstool#34]
I am trying to use *itstool* to translate the AppStream metadata file of my app called [Electrip](https://sourceforge.net/p/electrip/git/ci/master/tree/).

The reference XML file is *net.sourceforge.electrip.Electrip.appdata.xml* in the git repo linked above.
I use the default AppStream ITS-file from [here](https://www.freedesktop.org/software/appstream/docs/sect-Quickstart-Translation.html).

Executing the following *merge* command produces a translated XML in the directory *./appstream-translations* without problems:
```
itstool -i appdata-translations/appdata-translation-scheme.its -m appdata-translations/*.mo -o appdata-translations/ net.sourceforge.electrip.Electrip.appdata.xml
```

However the following *join* command leaves the XML untouched:
```
itstool -i appdata-translations/appdata-translation-scheme.its -j net.sourceforge.electrip.Electrip.appdata.xml -o net.sourceforge.electrip.Electrip.appdata.xml.translated appdata-translations/*.mo
```

If you could give me a quick heads-up about what I'm doing wrong I would be really glad!

**Comment by shaunix** [comment]
Confirmed bug. ITS files passed with -i aren't being applied under -j.

**Comment by shaunix** [comment]
Fixed in master. As a workaround if you can't update from git or wait for a release, you can trick itstool into thinking the AppStream ITS rules are built-in by putting the ITS file in `~/.local/share/itstool/its/`. No need to pass it with `-i` if you do that.
