### ISSUE TITLE
translate=no rules are ignored when creating the translated .xml 

### ISSUE THREAD

**Issue by tsdgeos** [itstool/itstool#37]
In the attached file there is a small xml file that say

```
<?xml version="1.0" encoding="utf-8"?>
<component type="desktop">
  <name>kmag</name>
  <not_name>kmag</not_name>
</component>

```
and an its file that says we only translate the name tag

```
<its:rules xmlns:its="http://www.w3.org/2005/11/its" version="1.0">
  <its:translateRule translate="no" selector="/component"/>
  <its:translateRule translate="yes" selector="/component/name"/>
</its:rules>
```

the generated .pot file looks good

 
```
  msgid ""
  msgstr ""
  "Project-Id-Version: PACKAGE VERSION\n"
  "POT-Creation-Date: 2019-03-08 00:17+0100\n"
  "PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
  "Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
  "Language-Team: LANGUAGE <LL@li.org>\n"
  "MIME-Version: 1.0\n"
  "Content-Type: text/plain; charset=UTF-8\n"
  "Content-Transfer-Encoding: 8bit\n"
  
  #. (itstool) path: component/name
  #: test.xml:3
  msgid "kmag"
  msgstr ""

``` 

And i've created a fake translation into ca.po that translate to cakmag

then when merging it with
`itstool -i test.its -j test.xml -o test.xml.translated ca.mo`
the generated translated with translates component/name and component/not_name too
```

<?xml version="1.0" encoding="utf-8"?>
<component type="desktop">
  <name>kmag</name>
  <name xml:lang="ca">cakmag</name>
  <not_name>kmag</not_name>
  <not_name xml:lang="ca">cakmag</not_name>
</component>

```

Seems to me as the rules in test.its are being ignored when they should not.

[itstool_bug.zip](https://github.com/itstool/itstool/files/2943748/itstool_bug.zip)

**Comment by shaunix** [comment]
Oh, interesting. I'll check on this over the weekend. Thanks.

**Comment by tsdgeos** [comment]
Did you have any luck reproducing/fixing it?

**Comment by shaunix** [comment]
Oh, can't believe I didn't recognize this. This is issue #34, which I fixed in November, but failed to roll a release with the fix. I'll do a release today.

**Comment by shaunix** [comment]
Version 2.0.6 released with the fix. Tarballs on itstool.org, also as an sdist on pypi.
http://itstool.org/download
