### ISSUE TITLE
xml:lang attribute not correct when MO files have @ in their name

### ISSUE THREAD

**Issue by jsynacek** [itstool/itstool#5]
```
<description>Send passphrase back to system</description>
<description xml:lang="be">Адправіць пароль назад сістэме</description>
<description xml:lang="be-Latn">Adpravić paroĺ nazad sistemie</description>
```
This snippet is generated from files named ```be.mo``` and ```be@latin.mo```. Note that the second generated attribute is not entirely correct. It should be "be@latin", the same as the file name.
In the corresponding "be@latin.po" file, there's
```
"Language: be@latin\n"
```
in the file.

**Comment by jsynacek** [comment]
Hmm, OK, I found that this is explicitely in the code (https://github.com/itstool/itstool/blob/master/itstool.in#L1384). Why is that?

**Comment by shaunix** [comment]
The xml:lang attribute is defined to take a BCP47 language identifier:

http://www.w3.org/TR/REC-xml/#sec-lang-tag
http://www.rfc-editor.org/rfc/bcp/bcp47.txt

itstool tries to bridge the different between BCP47 and gettext-style locales by allowing files to be named, managed, and installed according to gettext, but automatically converting the locale identifiers to BCP47 for xml:lang.

Is this causing problems?

**Comment by jsynacek** [comment]
No, for some reason I thought this was an error. Thank you for the explanation.
