### ISSUE TITLE
Fails to parse ITS of freedesktop's tutorial

### ISSUE THREAD

**Issue by BenWiederhake** [itstool/itstool#8]
I'm probably doing something wrong.

I'm using the ITS file and xml file from [this freedesktop quickstart page](http://www.freedesktop.org/software/appstream/docs/sect-Quickstart-Translation.html).

This doesn't work as intended, and instead produces the following error message:

    $ itstool -i as-metainfo.its -o the.metainfo.xml.pot the.metainfo.untranslated.xml
    Traceback (most recent call last):
      File "/usr/bin/itstool", line 1477, in <module>
        doc.apply_its_file(itsfile, params=params)
      File "/usr/bin/itstool", line 729, in apply_its_file
        doc = libxml2.parseFile(filename)
      File "/usr/lib/python2.7/dist-packages/libxml2.py", line 1341, in parseFile
        if ret is None:raise parserError('xmlParseFile() failed')
    libxml2.parserError: xmlParseFile() failed

Even if this is probably my error or some typo on freedesktop.org, I'd prefer its-tool to give me a clean error message, since I have no clue what is going wrong.

Steps to reproduce:

    git clone https://github.com/BenWiederhake/itstool-noparse.git
    cd itstool-noparse
    make

**Comment by shaunix** [comment]
What version of itstool?

```
itstool --version
```

I get this error:

```
Error: Could not parse document:
 the.metainfo.untranslated.xml:2:  parser  error :  Start tag expected, '<' not found
```

The code that catches the exception and gives you a (somewhat) nicer error message was added in 1.1.2.

**Comment by shaunix** [comment]
The parser error is because, for some reason, all of your lines start with U+200B. It's a zero-width space, so it won't show in many text editors, but XML parsers don't like to see it before the first element.

**Comment by BenWiederhake** [comment]
Argh! Sorry. I noticed and deleted the zero-width spaces before creating this issue, but forgot to upload the correct version to github. 

I no longer have access to the machine on which it failed, so I don't know the version there.

On my machine, I have:

    $ itstool --version
    itstool 2.0.2

And I can't recreate the problem on my machine. So in short: Sorry, my fault, it seems I didn't test it with the newest version first.

(For the record, if anyone has a similar problem like me: `gitk`'s *failure* to display the ZWP's makes it easier to see where they are, at least easier than viewing at a hexdump.)
